[DATABASE]
URL=postgresql://postgres.mvdpxnnsjyaovhqsyvzd:B3v7hWhmKmo27O2h@aws-0-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require

#[DATABASE]
#HOST=localhost
#PORT=5432
#DATABASE=db_risks_manage_full
#USER=postgres
#PASSWORD=123456

